services:
  - type: web
    name: ton-price-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8459761675:AAEqqjzhV3twVaxWF-d2UnT9MGcTLBwGTfc
      - key: CHANNEL_ID
        value: "@tonpricevery"
